name: groupWells
namespace: workflows/utils
description: |
  N/A
argument_groups:
  - name: Inputs
    arguments:
      - name: "--well"
        type: string
        description: Barcode identifier for a well
        required: true
        example: input.fastq.gz
      - name: "--input_r1"
        type: file
        description: Path to the input for R1
        required: true
        example: input.fastq.gz
      - name: "--input_r2"
        type: file
        description: Path to the input for R1
        required: true
        example: input.fastq.gz

  - name: Output
    arguments:
      - name: "--wells"
        type: string
        description: List of grouped wells (by means of barcodes)
        multiple: true
        direction: output
        example: input.fastq.gz
      - name: "--output_r1"
        type: file
        description: Path to output for R2
        multiple: true
        direction: output
      - name: "--output_r2"
        type: file
        description: Path to the output for R2
        multiple: true
        direction: output
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf

runners:
  - type: nextflow
